// <auto-generated />
using CoworkingWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoworkingWebApi.Migrations
{
    [DbContext(typeof(DbCoworkingContext))]
    [Migration("20210320133811_TablesMigration")]
    partial class TablesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoworkingWebApi.Models.DCoworking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("defaultPrice")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(Max)");

                    b.Property<string>("info")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("lat")
                        .HasColumnType("float");

                    b.Property<double>("lng")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ownerId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("DCoworkings");
                });

            modelBuilder.Entity("CoworkingWebApi.Models.DCoworkingFunction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("coworkingId")
                        .HasColumnType("int");

                    b.Property<bool>("isChair")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoffee")
                        .HasColumnType("bit");

                    b.Property<bool>("isCola")
                        .HasColumnType("bit");

                    b.Property<bool>("isSofa")
                        .HasColumnType("bit");

                    b.Property<bool>("isTable")
                        .HasColumnType("bit");

                    b.Property<bool>("isTea")
                        .HasColumnType("bit");

                    b.Property<double>("priceChair")
                        .HasColumnType("float");

                    b.Property<double>("priceCoffee")
                        .HasColumnType("float");

                    b.Property<double>("priceCola")
                        .HasColumnType("float");

                    b.Property<double>("priceSofa")
                        .HasColumnType("float");

                    b.Property<double>("priceTable")
                        .HasColumnType("float");

                    b.Property<double>("priceTea")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("DCoworkingFunctions");
                });

            modelBuilder.Entity("CoworkingWebApi.Models.DCoworkingOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("coworkingId")
                        .HasColumnType("int");

                    b.Property<string>("timeFinish")
                        .HasColumnType("nvarchar(Max)");

                    b.Property<string>("timeStart")
                        .HasColumnType("nvarchar(Max)");

                    b.Property<double>("totalCost")
                        .HasColumnType("float");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("DCoworkingOrders");
                });

            modelBuilder.Entity("CoworkingWebApi.Models.DFunction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("functionName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(Max)");

                    b.HasKey("id");

                    b.ToTable("DFunctions");
                });

            modelBuilder.Entity("CoworkingWebApi.Models.DUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("login")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("DUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
